import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Alias Medium Clone</title>
          <meta name="desscription" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Header */}
        <Header />

        {/* Hero Content */}
        <div className={styles.hero_container}>
          <div className={styles.hero_left}>
            <h1>
              <span className={styles.title}>Medium</span> is a place to write,
              read, and connect.
            </h1>
            <h3>
              It's easy and free to post your thinking on any topic and connect
              with millions of readers.
            </h3>
          </div>
          <img
            src="https://creativecommons.org/wp-content/uploads/2015/05/Medium-logo-dark500-300x300.png"
            alt="hero_medium logo"
          />
        </div>

        {/* Posts */}
      </div>
    </>
  );
}
